// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cufykawssrjdftlffuod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1ZnlrYXdzc3JqZGZ0bGZmdW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1Nzc1MjEsImV4cCI6MjA4MTE1MzUyMX0._cbGxRQu8hCBfASSvsJfQczq3dELfxXe3SG4GtJhZfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});