// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvdpqkakevsoknoxisse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2ZHBxa2FrZXZzb2tub3hpc3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjQwNjEsImV4cCI6MjA2OTIwMDA2MX0.HOLT2WXttQPoSdT2CWNpiCQ29NbhHA9fOR_TVHhOaXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});